version: '3.8'

services:
  mongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"

  redis:
    image: redis:4
    ports:
      - "6379:6379"
